// Names that don't count as a "hobby to cultivate" under the app's own
// constitution: video games and social-media/short-video apps are screen
// time, not something this app exists to help someone build. Profanity is
// blocked for the same reason a real teacher would reject it on a form.
const BLOCKED_TERMS = [
  // generic screen-time terms
  "video game", "videogame", "gaming", "gamer", "esports", "e-sports",
  "电竞", "游戏", "手游", "端游", "网游",
  // games popular with Chinese teens specifically, since this build targets
  // local Chinese users
  "honor of kings", "王者荣耀", "王者",
  "pubg", "和平精英", "吃鸡",
  "genshin", "原神",
  "minecraft", "我的世界",
  "league of legends", "英雄联盟",
  "crossfire", "穿越火线",
  "knives out", "荒野行动",
  "identity v", "第五人格",
  "sky: children of the light", "光遇",
  "onmyoji", "阴阳师",
  "honkai", "崩坏",
  "eggy party", "蛋仔派对",
  "roblox", "罗布乐思",
  "fortnite", "堡垒之夜",
  "free fire",
  // social media / short video
  "tiktok", "抖音", "douyin",
  "kuaishou", "快手",
  "weibo", "微博",
  "wechat moments", "朋友圈",
  "xiaohongshu", "小红书", "rednote",
  "instagram", "照片墙",
  "facebook", "脸书",
  "snapchat",
  "twitter", "推特",
  "bilibili", "哔哩哔哩", "b站",
  "youtube", "油管",
];

// Curse words and slurs. Each one lists the realistic single-character
// censorship spellings people actually type (an asterisk standing in for
// one letter — "f*ck", "sh*t"), hand-checked one at a time rather than
// generated by a live wildcard pattern. A generic wildcard match ("f*ck"
// matches anything shaped like f.ck) previously caught innocent words too —
// "*uck" matched "duck" and "luck" just as well as "fuck". Matching only
// this fixed, manually-verified list of exact spellings closes that gap:
// nothing gets blocked unless it is either a clean word from this list, or
// one of the specific censored spellings written out below.
//
// Short words (ass, dick, cock, piss, twat) are deliberately whole-word-only
// — never substring-matched — since they're real substrings of ordinary
// words ("class", "peacock", "predict").
const CURSE_WHOLE_WORD_ONLY = [
  "ass", "dick", "cock", "piss", "twat",
];
const CURSE_WORDS = [
  ["fuck", ["f*ck", "fu*k", "fuc*"]],
  ["shit", ["sh*t", "s*it"]],
  ["bitch", ["b*tch", "bi*ch"]],
  ["asshole", ["a**hole", "a*shole"]],
  ["cunt", ["c*nt"]],
  ["bastard", ["b*stard"]],
  ["whore", ["wh*re"]],
  ["slut", ["sl*t"]],
  ["pussy", ["p*ssy"]],
  ["nigger", ["n*gger"]],
  ["nigga", ["n*gga"]],
  ["faggot", ["f*ggot"]],
  ["retard", ["r*tard"]],
  ["dumbass", ["dumb*ss"]],
  ["操你", []],
  ["草你", []],
  ["他妈的", []],
  ["妈的", []],
  ["你妈", []],
  ["尼玛", []],
  ["傻逼", ["傻*", "*逼"]],
  ["煞笔", []],
  ["沙比", []],
  ["婊子", []],
  ["贱人", []],
  ["王八蛋", []],
  ["混蛋", []],
  ["死全家", []],
  ["妈逼", []],
  ["弱智", []],
  ["智障", []],
  ["狗日的", []],
];

// Every exact spelling (clean word, censored variant, or whole-word-only
// term) that counts as a match when a typed name equals it exactly as one
// "word".
const WHOLE_WORD_LOOKUP = new Set(CURSE_WHOLE_WORD_ONLY);
CURSE_WORDS.forEach(([clean, variants]) => {
  WHOLE_WORD_LOOKUP.add(clean);
  variants.forEach((v) => WHOLE_WORD_LOOKUP.add(v));
});

function containsCurseWord(name) {
  const words = name.split(/[\s,，、.!?！？~～\-_/]+/).filter(Boolean);
  if (words.some((w) => WHOLE_WORD_LOOKUP.has(w))) return true;
  // Clean (uncensored) words can still show up glued to other text with no
  // separator ("fuckthis") — substring-match those directly. Never do this
  // for the censored variants or the whole-word-only list: substring-
  // matching "f*ck" or "ass" would defeat the point of requiring a whole
  // word and reintroduce false positives like "class" or "peacock".
  return CURSE_WORDS.some(([clean]) => name.includes(clean));
}

export function isBlockedHobby(name) {
  const n = String(name || "").trim().toLowerCase();
  if (!n) return false;
  if (BLOCKED_TERMS.some((term) => n.includes(term))) return true;
  return containsCurseWord(n);
}
