// Profanity and slurs, shared by everything in the app that accepts typed
// text. Lifted out of hobbyFilter.js, which is where it was written and
// where it was doing only a fraction of its job: it screened hobby *names*
// and nothing else, so journal entries and photo captions — the text that
// actually reaches other children — went out completely unchecked.
//
// This module is the client half. The server keeps its own copy in
// public.blocked_terms and enforces it on anything published (see migration
// 20260920000000), because a check that only runs in the browser is a
// suggestion. This copy exists so a student finds out before they tap
// Share rather than after a round trip.

// Curse words and slurs. Each one lists the realistic single-character
// censorship spellings people actually type (an asterisk standing in for
// one letter — "f*ck", "sh*t"), hand-checked one at a time rather than
// generated by a live wildcard pattern. A generic wildcard match ("f*ck"
// matches anything shaped like f.ck) previously caught innocent words too —
// "*uck" matched "duck" and "luck" just as well as "fuck". Matching only
// this fixed, manually-verified list of exact spellings closes that gap:
// nothing gets blocked unless it is either a clean word from this list, or
// one of the specific censored spellings written out below.
//
// Short words (ass, dick, cock, piss, twat) are deliberately whole-word-only
// — never substring-matched — since they're real substrings of ordinary
// words ("class", "peacock", "predict").
const CURSE_WHOLE_WORD_ONLY = [
  "ass", "dick", "cock", "piss", "twat",
];
const CURSE_WORDS = [
  ["fuck", ["f*ck", "fu*k", "fuc*"]],
  ["shit", ["sh*t", "s*it"]],
  ["bitch", ["b*tch", "bi*ch"]],
  ["asshole", ["a**hole", "a*shole"]],
  ["cunt", ["c*nt"]],
  ["bastard", ["b*stard"]],
  ["whore", ["wh*re"]],
  ["slut", ["sl*t"]],
  ["pussy", ["p*ssy"]],
  ["nigger", ["n*gger"]],
  ["nigga", ["n*gga"]],
  ["faggot", ["f*ggot"]],
  ["retard", ["r*tard"]],
  ["dumbass", ["dumb*ss"]],
  ["操你", []],
  ["草你", []],
  ["他妈的", []],
  ["妈的", []],
  ["你妈", []],
  ["尼玛", []],
  ["傻逼", ["傻*", "*逼"]],
  ["煞笔", []],
  ["沙比", []],
  ["婊子", []],
  ["贱人", []],
  ["王八蛋", []],
  ["混蛋", []],
  ["死全家", []],
  ["妈逼", []],
  ["弱智", []],
  ["智障", []],
  ["狗日的", []],
];

// Every exact spelling (clean word, censored variant, or whole-word-only
// term) that counts as a match when a typed name equals it exactly as one
// "word".
const WHOLE_WORD_LOOKUP = new Set(CURSE_WHOLE_WORD_ONLY);
CURSE_WORDS.forEach(([clean, variants]) => {
  WHOLE_WORD_LOOKUP.add(clean);
  variants.forEach((v) => WHOLE_WORD_LOOKUP.add(v));
});

function containsCurseWord(name) {
  const words = name.split(/[\s,，、.!?！？~～\-_/]+/).filter(Boolean);
  if (words.some((w) => WHOLE_WORD_LOOKUP.has(w))) return true;
  // Clean (uncensored) words can still show up glued to other text with no
  // separator ("fuckthis") — substring-match those directly. Never do this
  // for the censored variants or the whole-word-only list: substring-
  // matching "f*ck" or "ass" would defeat the point of requiring a whole
  // word and reintroduce false positives like "class" or "peacock".
  return CURSE_WORDS.some(([clean]) => name.includes(clean));
}

// Free text: a journal entry, a photo caption. Case-folded and matched the
// same way a hobby name is, so the rules cannot drift between the two.
export function containsProfanity(text) {
  const t = String(text || "").trim().toLowerCase();
  if (!t) return false;
  return containsCurseWord(t);
}
